source 'https://cdn.cocoapods.org/'

platform :ios, '10.0'

use_frameworks!

target 'Example' do
  pod 'StepTracking', :path => '../'
  pod 'StepTracking/RxTracking', :path => '../'
  
  pod 'RxCocoa'
  pod 'Firebase/Analytics'
end
